- name: DevSecOps
  hosts: servidor
  become: yes #roda como root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        force_apt_get: yes
        upgrade: dist

    - name: Instalar dependências do sistema
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - gnupg
        state: present

    - name: Baixar chave GPG do Docker
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc

    - name: Adicionar repositório Docker
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Atualizar apt novamente
      apt:
        update_cache: yes

    - name: Insatalar docker para Python
      pip:
        name: docker
        state: present 
        
    - name: Instalar Docker Engine e Docker Compose Plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
    
    - name: Garantir que o Docker está rodando
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copiar Docker Compose para o servidor
      copy:
        src: ../docker/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Rodar Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: present
        pull: always
      