#maestro: github actions
#a cada push na branch main, um robo aciona uma VM para executar estes comandos
#workflow customizado para segurança

name: DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Instalar dependências de teste
        run: |
          pip install flake8 bandit
        
      - name: Rodar Linter (Flake8)
        run: flake8 ./app --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Rodar Análise de segurança (Bandit)
        run: bandit -r ./app -f txt


  build-and-push:
    needs: security-and-testing
    runs-on: ubuntu-latest

    steps:
    - name: Configurando credenciais AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login no ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build e Push das imagens
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/gunicorn-app-flask:latest -f ./dockerf.gunicorn ./app
        docker push $ECR_REGISTRY/gunicorn-app-flask:latest

        docker build -t $EC_REGISTRY/nginx-app-flask:latest -f ./dockerf.nginx .
        docker push $ECR_REGISTRY/nginx-app-flask:latest

        docker build -t $ECR_REGISTRY/netdata-repo:latest -f ./dockerf.netdata .
        docker push $ECR_REGISTRY/netdata-repo:latest
